#!/usr/bin/env bash
set -euo pipefail
LIBERO_SUITE="${LIBERO_SUITE:-spatial}"
case "${LIBERO_SUITE}" in
  spatial|object|goal|10) ;;
  *)
    echo "LIBERO_SUITE must be one of: spatial, object, goal, 10" >&2
    exit 1
    ;;
esac
PRECOMPUTE_STORAGE_FORMAT="${PRECOMPUTE_STORAGE_FORMAT:-episode_packed_v1}"
PRECOMPUTE_BATCH_SIZE="${PRECOMPUTE_BATCH_SIZE:-256}"
PRECOMPUTE_HISTORY_ENCODE_BATCH_SIZE="${PRECOMPUTE_HISTORY_ENCODE_BATCH_SIZE:-1024}"
PRECOMPUTE_NUM_WORKERS="${PRECOMPUTE_NUM_WORKERS:-0}"
export PRECOMPUTE_STORAGE_FORMAT PRECOMPUTE_BATCH_SIZE
export PRECOMPUTE_HISTORY_ENCODE_BATCH_SIZE PRECOMPUTE_NUM_WORKERS
TARGET="libero_${LIBERO_SUITE}" bash "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/precompute.sh" "$@"
